/**
 * Textos da tela de Cadastros em inglês (en-GB, só existe no mercado Portugal).
 *
 * A chave é o próprio texto em português. Fora de en-GB a tradução devolve o
 * texto de entrada SEM alteração -- e isso inclui o Brasil, para o qual o
 * LocaleContext também responde 'pt-PT'. Assim nenhuma tela brasileira muda de
 * texto por causa desta camada: o pior caso de uma chave esquecida é o inglês
 * mostrar o português, nunca o português mudar.
 *
 * `{nome}` no texto é substituído por `vars.nome` nos dois idiomas.
 *
 * "Lojista", "Corporativo" e "PVP" são nomes comerciais e ficam iguais em
 * inglês, como no catálogo e no orçamento.
 */
const EN: Record<string, string> = {
  // navegação
  'Cadastros': 'Records',
  'Produtos': 'Products',
  'Clientes': 'Clients',
  'Representantes': 'Representatives',
  'Opcionais': 'Options',
  'Grupos & Subgrupos': 'Groups & subgroups',
  'Catálogos': 'Catalogues',
  'Importação CSV': 'CSV import',

  // comuns
  'Cancelar': 'Cancel',
  'Excluir': 'Delete',
  'Editar': 'Edit',
  'Salvar': 'Save',
  'Criar': 'Create',
  'Fechar': 'Close',
  'Visualizar': 'View',
  'Carregando...': 'Loading...',
  'Carregando…': 'Loading…',
  'Salvando...': 'Saving...',
  'Confirmar exclusão': 'Confirm deletion',
  '? Esta ação não pode ser desfeita.': '? This cannot be undone.',
  'Anterior': 'Previous',
  'Próximo': 'Next',
  'Página': 'Page',
  'de': 'of',
  'Nome': 'Name',
  'Nome *': 'Name *',
  'Telefone': 'Phone',
  'Telefone *': 'Phone *',
  'E-mail': 'Email',
  'Código postal *': 'Postcode *',
  'Número': 'Number',
  'Endereço': 'Address',
  'Endereço *': 'Address *',
  'Localidade *': 'Town / city *',
  'País da primeira liberação': 'Launch country',
  'Região': 'Region',
  'Cidade': 'City',
  'Estado': 'State',
  'UF': 'State',
  'CEP': 'Postcode',

  // colunas redimensionáveis
  'Redimensionar coluna {label}': 'Resize column {label}',
  'Arraste para redimensionar · Duplo clique para autoajustar': 'Drag to resize · Double-click to auto-fit',

  // fotos em lote
  'Upload de Fotos em Lote': 'Batch photo upload',
  'SKU {sku} repetido na seleção': 'SKU {sku} repeated in the selection',
  'SKU não encontrado': 'SKU not found',
  'Não foi possível validar os códigos dos arquivos. Tente novamente.': 'Could not validate the file codes. Please try again.',
  'Não foi possível ler os arquivos selecionados.': 'Could not read the selected files.',
  'Arraste uma pasta ou arquivos de fotos aqui': 'Drag a folder or photo files here',
  'O nome do arquivo deve ser o código do produto (ex.: IML0001.png)': 'The file name must be the product code (e.g. IML0001.png)',
  'Selecionar pasta': 'Select folder',
  'Selecionar arquivos': 'Select files',
  'Validando códigos no catálogo…': 'Checking codes against the catalogue…',
  '{count} validada(s)': '{count} accepted',
  '{count} rejeitada(s)': '{count} rejected',
  'Aguardando': 'Waiting',
  'Enviando…': 'Uploading…',
  'Enviada': 'Uploaded',
  'Erro': 'Error',
  'Enviando… {progress}%': 'Uploading… {progress}%',
  'Iniciar Upload ({count})': 'Start upload ({count})',

  // produtos
  'produto': 'product',
  'produtos': 'products',
  'Buscar produtos por código ou descrição': 'Search products by code or name',
  'Buscar por código ou descrição...': 'Search by code or name...',
  'Todos os Catálogos': 'All catalogues',
  'Novo ': 'New ',
  'Produto': 'Product',
  'Em Portugal, pode cadastrar produtos exclusivos deste mercado, editar os nomes em português e inglês e os preços em EUR; excluir remove o produto apenas deste catálogo.':
    'In Portugal you can add products exclusive to this market and edit the Portuguese and English names and the prices in EUR; deleting removes the product from this catalogue only.',
  'Nenhum produto encontrado com este filtro.': 'No products match this filter.',
  'Nenhum produto cadastrado.': 'No products yet.',
  'Arraste os divisores para redimensionar ou dê duplo clique para autoajustar.': 'Drag the dividers to resize or double-click to auto-fit.',
  'Distribuir as colunas dentro da largura disponível': 'Fit the columns to the available width',
  'Ajustar à tela': 'Fit to screen',
  'Voltar às larguras padrão': 'Restore default widths',
  'Restaurar': 'Reset',
  'Código': 'Code',
  'Descrição': 'Description',
  'Dimensões': 'Dimensions',
  'Foto': 'Photo',
  'Todos': 'All',
  'Novo Tipo de Móvel': 'New furniture type',
  'Tipo já existe ou nome inválido.': 'Type already exists or the name is invalid.',
  'Nome do Novo Tipo *': 'New type name *',
  'Criar e Selecionar': 'Create and select',
  'Editar Produto em Portugal': 'Edit product in Portugal',
  'Os nomes e os preços abaixo pertencem apenas a Portugal; o catálogo do Brasil não é alterado.':
    'The names and prices below belong to Portugal only; the Brazilian catalogue is not changed.',
  'Nome em português (Portugal)': 'Name in Portuguese (Portugal)',
  'Nome em inglês': 'Name in English',
  'Nome em inglês *': 'Name in English *',
  'A guardar…': 'Saving…',
  'Guardar nomes e preços': 'Save names and prices',
  'Editar Produto': 'Edit product',
  'Novo Produto em Portugal': 'New product in Portugal',
  'Novo Produto': 'New product',
  'Código *': 'Code *',
  'Preço Lojista ({currency}) *': 'Lojista price ({currency}) *',
  'Preço Corporativo ({currency}) *': 'Corporativo price ({currency}) *',
  'Preço PVP (€) *': 'PVP price (€) *',
  'Observação': 'Notes',
  'Informações técnicas, restrições, montagem...': 'Technical details, restrictions, assembly...',
  'Tipo': 'Type',
  '+ Adicionar Novo...': '+ Add new...',
  'Catálogo': 'Catalogue',
  'Sem catálogo': 'No catalogue',
  'Medida Redonda (Ø — circular)': 'Round (Ø — circular)',
  'Diâmetro Ø (m) *': 'Diameter Ø (m) *',
  'Altura A (m) *': 'Height H (m) *',
  'Largura L (m) *': 'Width W (m) *',
  'Prof. P (m) *': 'Depth D (m) *',
  'Componentes do Conjunto': 'Set components',
  'Editar Componente': 'Edit component',
  'Novo Componente': 'New component',
  'Descrição *': 'Description *',
  'ex: Sofá 3 lugares, Poltrona, Mesa...': 'e.g. 3-seater sofa, armchair, table...',
  'Medida Redonda (Ø)': 'Round (Ø)',
  'Diâmetro Ø (m)': 'Diameter Ø (m)',
  'Altura A (m)': 'Height H (m)',
  'L (m)': 'W (m)',
  'P (m)': 'D (m)',
  'A (m)': 'H (m)',
  'Quantidade': 'Quantity',
  'Opcionais do Componente': 'Component options',
  'Nenhum grupo de opcionais cadastrado. Crie grupos na aba Opcionais.': 'No option groups yet. Create groups in the Options tab.',
  'Salvar Componente': 'Save component',
  'Adicionar Componente': 'Add component',
  'Código do produto': 'Product code',
  'Código deve existir no catálogo. Conjuntos não podem conter outros conjuntos.': 'The code must exist in the catalogue. Sets cannot contain other sets.',
  'Categorias de Opcionais Disponíveis': 'Available option categories',
  'Cores e Permissões por Categoria': 'Colours and permissions by category',
  'Permitir todos': 'Allow all',
  'Todos os opcionais desta categoria estarão disponíveis no carrinho.': 'Every option in this category will be available in the cart.',
  'Nenhuma cor cadastrada nesta categoria.': 'No colours in this category yet.',
  'Ctrl+clique para selecionar múltiplas cores.': 'Ctrl+click to select several colours.',
  'Clique para trocar': 'Click to change',
  'JPG, PNG, WEBP — máx. 5MB': 'JPG, PNG, WEBP — max. 5MB',
  '{name} do catálogo Portugal': '{name} from the Portugal catalogue',

  // clientes e representantes
  'Erro ao criar usuário.': 'Error creating the user.',
  '{count} {label} cadastrados': '{count} {label}',
  'Buscar por nome...': 'Search by name...',
  'Sem e-mail': 'No email',
  'Criado por:': 'Created by:',
  'cadastro anterior': 'earlier record',
  'Nenhum registro encontrado com este filtro.': 'No records match this filter.',
  'Nenhum registro encontrado.': 'No records found.',
  'Desc. Máx.': 'Max. disc.',
  'Criado por': 'Created by',
  'Cadastro anterior': 'Earlier record',
  'Detalhes — {name}': 'Details — {name}',
  'Não informado': 'Not provided',
  'Cadastro anterior ao rastreamento': 'Created before tracking',
  'Acesso ao Sistema': 'System access',
  'Usuário criado com sucesso!': 'User created successfully!',
  'Usuário:': 'Username:',
  'Senha inicial:': 'Initial password:',
  'Perfil:': 'Profile:',
  'Representante': 'Representative',
  'Cliente': 'Client',
  'O usuário deverá trocar a senha no primeiro acesso.': 'The user must change the password on first sign-in.',
  'Usuário já criado': 'User already created',
  'Gerencie pela tela Admin.': 'Manage it in the Admin screen.',
  'Criando…': 'Creating…',
  'Criar Usuário': 'Create user',
  'Cria acesso com usuário gerado pelo nome e senha temporária aleatória.': 'Creates access with a username based on the name and a random temporary password.',
  'Conta pendente. Um administrador deve confirmar o e-mail do titular e enviar o convite.':
    'Account pending. An administrator must confirm the holder’s email and send the invitation.',
  'Aguardando ativação pelo titular.': 'Waiting for the holder to activate it.',
  'Solicita a conta. A senha será definida pelo titular após confirmação do e-mail por um administrador.':
    'Requests the account. The holder sets the password once an administrator confirms the email.',
  'Confirme a identidade do titular fora do sistema antes de enviar. Digite o e-mail que foi verificado; ele deve coincidir com o cadastro.':
    'Confirm the holder’s identity outside the system before sending. Type the email you verified; it must match the record.',
  'E-mail confirmado do titular': 'Holder’s confirmed email',
  'Método de verificação': 'Verification method',
  'Retorno telefônico ao titular': 'Call back to the holder',
  'Contrato existente': 'Existing contract',
  'Verificação presencial': 'In-person check',
  'Confirmar e enviar convite': 'Confirm and send invitation',
  'Convite enviado ao endereço confirmado.': 'Invitation sent to the confirmed address.',
  'Editar {item}': 'Edit {item}',
  'Novo {item}': 'New {item}',
  'Perfil de faturamento *': 'Billing profile *',
  'Desconto Máximo (%)': 'Maximum discount (%)',
  'Os dados coletados neste formulário são processados estritamente para a elaboração de orçamentos e gestão do pedido, conforme a nossa Política de Privacidade.':
    'The data collected in this form is processed strictly to prepare quotes and manage orders, in line with our Privacy Policy.',

  // opcionais
  '{count} opcionais cadastrados': '{count} options',
  'Adicionar Grupos': 'Add groups',
  'Crie um grupo primeiro': 'Create a group first',
  'Novo Opcional': 'New option',
  'grupo não cadastrado': 'group not registered',
  'Editar grupo': 'Edit group',
  'Excluir grupo': 'Delete group',
  'Cadastrar grupo': 'Register group',
  'Nenhuma cor cadastrada.': 'No colours yet.',
  'Nenhum grupo cadastrado. Clique em "Adicionar Grupos" para começar.': 'No groups yet. Click "Add groups" to start.',
  'Swatch ampliado': 'Enlarged swatch',
  'Editar Opcional': 'Edit option',
  'Categoria *': 'Category *',
  'Nome da Cor *': 'Colour name *',
  'Imagem de Textura (swatch)': 'Texture image (swatch)',
  'PNG, JPG — textura do material': 'PNG, JPG — material texture',
  'Editar Grupo': 'Edit group',
  'Novo Grupo de Opcionais': 'New option group',
  'Nome do Grupo *': 'Group name *',
  'ex: Alumínio': 'e.g. Aluminium',
  'Código (identificador único) *': 'Code (unique identifier) *',
  'ex: aluminio': 'e.g. aluminium',
  'Apenas letras minúsculas, números e underscores.': 'Lowercase letters, numbers and underscores only.',
  'Criar Grupo': 'Create group',
  'Código já existe ou dados inválidos.': 'Code already exists or the data is invalid.',
  'cor': 'colour',
  'cores': 'colours',

  // grupos e subgrupos
  'Erro ao salvar grupo.': 'Error saving the group.',
  'Erro ao salvar subgrupo.': 'Error saving the subgroup.',
  'Novo Grupo': 'New group',
  'Alíquota IPI (%)': 'IPI rate (%)',
  'Salvar Alterações': 'Save changes',
  'Editar Subgrupo': 'Edit subgroup',
  'Novo Subgrupo': 'New subgroup',
  'Nome do Subgrupo *': 'Subgroup name *',
  'Grupo': 'Group',
  'Sem grupo': 'No group',
  'Criar Subgrupo': 'Create subgroup',
  'Nenhum grupo cadastrado.': 'No groups yet.',

  // catálogos
  'Informe o nome do catálogo.': 'Enter the catalogue name.',
  'Erro ao salvar catálogo.': 'Error saving the catalogue.',
  'Erro ao excluir catálogo.': 'Error deleting the catalogue.',
  'Linhas comerciais usadas como filtro na tela de Produtos.': 'Product lines used as a filter on the Products screen.',
  'Novo Catálogo': 'New catalogue',
  'Nenhum catálogo cadastrado.': 'No catalogues yet.',
  'Editar Catálogo': 'Edit catalogue',
  'Ex.: Cerâmica': 'e.g. Ceramics',
  'Excluir Catálogo': 'Delete catalogue',
  'Excluir o catálogo': 'Delete the catalogue',

  // importação
  'Falha ao processar o arquivo. Verifique o formato do CSV.': 'Failed to process the file. Check the CSV format.',
  'Colunas:': 'Columns:',
  'Selecionar arquivo CSV de {label}': 'Select CSV file for {label}',
  'Enviando...': 'Uploading...',
  'Importar': 'Import',
  'linhas processadas': 'rows processed',
  'criadas': 'created',
  'atualizadas': 'updated',
  'Arquivo rejeitado — nada foi importado. Corrija {count} {errors} em {rows} linhas e reenvie.':
    'File rejected — nothing was imported. Fix {count} {errors} in {rows} rows and upload again.',
  'erro': 'error',
  'erros': 'errors',
  'Linha {row}: {message}': 'Row {row}: {message}',
  'Importe cadastros em massa via arquivos .csv (UTF-8; separador vírgula ou ponto-e-vírgula). Reimportações atualizam registros existentes pela chave (nome, SKU ou e-mail).':
    'Import records in bulk from .csv files (UTF-8; comma or semicolon separator). Re-imports update existing records by key (name, SKU or email).',
  'Cadastros de apoio': 'Supporting records',
  'Tabela:': 'Table:',
  'Grupos de Produto': 'Product groups',
  'Tipos de Produto': 'Product types',
  'name, phone, email (opcional), cpf_cnpj (opcional), cep, numero, address, city, state':
    'name, phone, email (optional), cpf_cnpj (optional), cep, numero, address, city, state',
  'name, phone, email (opcional), cpf_cnpj (opcional), cep, numero, address, city, state, price_profile, rep_email':
    'name, phone, email (optional), cpf_cnpj (optional), cep, numero, address, city, state, price_profile, rep_email',
  'Catálogo de produtos — 2 etapas': 'Product catalogue — 2 steps',
  'Etapa 1: Subir Tabela de Produtos': 'Step 1: Upload the product table',
  'Cria/atualiza produtos pelo SKU (product_code).': 'Creates/updates products by SKU (product_code).',
  'Etapa 2: Subir Tabela de Opcionais do Produto': 'Step 2: Upload the product options table',
  'Vincula opcionais a cada SKU — rode após a Etapa 1.': 'Links options to each SKU — run after Step 1.',
  'Selecione a pasta com as fotos — o nome de cada arquivo deve ser o código do produto (ex.: IML0001.png); a foto é associada automaticamente ao produto correspondente.':
    'Select the folder with the photos — each file name must be the product code (e.g. IML0001.png); the photo is linked to the matching product automatically.',
  'Importar Foto': 'Import photo',
  'Painel de dados': 'Data panel',
}

export type CadastroTextVars = Record<string, string | number>

export function translateCadastro(locale: string, pt: string, vars?: CadastroTextVars): string {
  const template = locale === 'en-GB' ? (EN[pt] ?? pt) : pt
  if (!vars) return template
  return template.replace(/\{(\w+)\}/g, (match, key: string) =>
    key in vars ? String(vars[key]) : match,
  )
}

/** Exposto para teste: as chaves do dicionário. */
export const CADASTRO_EN_KEYS = Object.keys(EN)
