import type { AxiosAdapter, AxiosResponse } from 'axios'
import api, { authApi } from './api'
import type { AuthUser } from '../contexts/AuthContext'

const demoRequested = new URLSearchParams(window.location.search).get('demo') === '1'
if (demoRequested) sessionStorage.setItem('ilya-demo-mode', '1')
export const DEMO_MODE = demoRequested || sessionStorage.getItem('ilya-demo-mode') === '1'
export const DEMO_USER: AuthUser = { id: 'demo-admin', email: 'demo@oramo.com.br', username: 'demo', full_name: 'Marina — Demonstração', role: 'admin', rep_id: null, linked_id: null, is_active: true, must_change_password: false, max_discount: 20, can_view_dashboard: true, home_market: 'BR', active_market: 'BR', allowed_markets: ['BR', 'EU'] }
const now = new Date().toISOString()
const image = (label: string, color: string) => `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="900" height="700"><rect width="100%" height="100%" fill="${color}"/><path d="M170 470h560v45H170zM230 310h440v170H230z" fill="#fff" opacity=".28"/><text x="50%" y="85%" text-anchor="middle" fill="#fff" font-family="Georgia" font-size="42">${label}</text></svg>`)}`
const optionals = [{ id: 'o1', category: 'MADEIRA', color_name: 'Nogueira Natural', photo_url: image('Nogueira', '#76553d') }, { id: 'o2', category: 'TECIDO', color_name: 'Linho Areia', photo_url: image('Linho Areia', '#b5a48b') }, { id: 'o3', category: 'METAL', color_name: 'Champagne', photo_url: image('Champagne', '#a98b55') }]
const products = [['IL-101','Poltrona Alba','POLTRONAS',6840,'#8f755e'],['IL-204','Sofá Horizonte','SOFÁS',12980,'#82766a'],['IL-315','Mesa de Centro Íris','MESAS',5290,'#9b7b55'],['IL-408','Cadeira Serena','CADEIRAS',3780,'#797165'],['IL-512','Aparador Atlas','APARADORES',8450,'#62584f'],['IL-607','Mesa de Jantar Orbe','MESAS',14890,'#6e5845']].map(([code, description, type, price, color], index) => ({ id: `p${index + 1}`, product_code: code, description, type, is_circular: false, is_set: false, altura: .82, largura: index % 2 ? 1.8 : .78, profundidade: .76, price, price_lojista: price, price_corporativo: Number(price) * .92, observacao: index === 1 ? 'Configuração modular disponível.' : null, all_optionals_categories: null, optionals, set_items: [], components: [], photo_url: image(String(description), String(color)), thumbnail_url: image(String(description), String(color)), created_at: now, updated_at: now }))
const reps = [{ id: 'r1', name: 'André Menezes', phone: '(11) 98888-1200', email: 'andre@oramo.com.br', cpf_cnpj: '123.456.789-00', cep: '01415-001', numero: '120', address: 'Alameda Santos', city: 'São Paulo', state: 'SP', price_profile: 'lojista', max_discount: 15, rep_id: null, created_at: now, updated_at: now, last_activity_at: now, relationship_ended_at: null, has_user: true }, { id: 'r2', name: 'Bianca Rocha', phone: '(21) 97777-2400', email: 'bianca@oramo.com.br', cpf_cnpj: '987.654.321-00', cep: '22410-003', numero: '80', address: 'Rua Garcia d’Ávila', city: 'Rio de Janeiro', state: 'RJ', price_profile: 'lojista', max_discount: 12, rep_id: null, created_at: now, updated_at: now, last_activity_at: now, relationship_ended_at: null, has_user: true }]
const clients = [{ id: 'c1', name: 'Studio Lumina', phone: '(11) 3333-2211', email: 'contato@studiolumina.com', cpf_cnpj: '12.345.678/0001-90', cep: '01414-001', numero: '450', address: 'Rua Haddock Lobo', city: 'São Paulo', state: 'SP', price_profile: 'corporativo', max_discount: 10, rep_id: 'r1', created_at: now, updated_at: now, last_activity_at: now, has_user: false, created_by_name: 'Marina — Demonstração' }, { id: 'c2', name: 'Casa Castro Interiores', phone: '(41) 3222-8899', email: 'projetos@castro.com.br', cpf_cnpj: '23.456.789/0001-01', cep: '80420-090', numero: '72', address: 'Alameda Dr. Carlos de Carvalho', city: 'Curitiba', state: 'PR', price_profile: 'lojista', max_discount: 8, rep_id: 'r2', created_at: now, updated_at: now, last_activity_at: now, has_user: true, created_by_name: 'Marina — Demonstração' }]
const users = [DEMO_USER, { ...DEMO_USER, id: 'u2', email: 'andre@oramo.com.br', username: 'andre', full_name: 'André Menezes', role: 'representante', rep_id: 'r1', can_view_dashboard: false }]
const orderItems = [{ id: 'i1', order_id: 'ord1', product_code: 'IL-204', description: 'Sofá Horizonte', is_circular: false, altura: .82, largura: 1.8, profundidade: .76, opt_categories: { TECIDO: 'Linho Areia' }, qty: 2, unit_price: 12980, discount: 5, ipi_rate: 5, ipi_value: 1233.1, observacao: null, created_at: now, updated_at: now }]
const orders = [{ id: 'ord1', code: 'PED-00024', orc_id: 'ORC-00031', client_id: 'c1', client_name: 'Studio Lumina', rep_id: 'r1', rep_name: 'André Menezes', total_value: 24662, total_ipi: 1233.1, total_with_ipi: 25895.1, is_finalized: true, is_cancelled: false, finalized_at: now, cancelled_at: null, external_code: 'OC-5412', notes: 'Entrega agendada com a arquitetura.', rep_signed: true, client_signed: false, items: orderItems, history: [], created_at: now, updated_at: now }, { id: 'ord2', code: 'PED-00025', orc_id: 'ORC-00032', client_id: 'c2', client_name: 'Casa Castro Interiores', rep_id: 'r2', rep_name: 'Bianca Rocha', total_value: 14890, total_ipi: 744.5, total_with_ipi: 15634.5, is_finalized: false, is_cancelled: false, finalized_at: null, cancelled_at: null, external_code: null, notes: null, rep_signed: false, client_signed: false, items: [], history: [], created_at: now, updated_at: now }]
const response = (config: Parameters<AxiosAdapter>[0], data: unknown, headers: Record<string, string> = {}): AxiosResponse => ({ data, status: 200, statusText: 'OK', headers, config, request: {} })
const byId = (items: any[], url: string) => items.find(item => url.endsWith(`/${item.id}`) || url.endsWith(`/${item.code}`))
const adapter: AxiosAdapter = async config => {
  const url = String(config.url ?? '').split('?')[0]
  if (url === '/auth/me') return response(config, DEMO_USER)
  if (url === '/auth/login' || url === '/auth/refresh') return response(config, { access_token: 'demo-token' })
  if (url === '/notifications') return response(config, [{ id: 'n1', message: 'Novo orçamento aguardando revisão.', is_read: false, created_at: now }])
  if (url === '/products/batch') return response(config, products)
  if (url === '/products') return response(config, products, { 'x-total-count': String(products.length), 'x-page-size': String(products.length), 'x-has-more': 'false' })
  if (url === '/clients') return response(config, clients, { 'x-total-count': String(clients.length) })
  if (url.startsWith('/clients/')) return response(config, byId(clients, url) ?? clients[0])
  if (url === '/representatives') return response(config, reps, { 'x-total-count': String(reps.length) })
  if (url.startsWith('/representatives/')) return response(config, byId(reps, url) ?? reps[0])
  if (url === '/users') return response(config, users, { 'x-total-count': String(users.length) })
  if (url === '/optionals') return response(config, optionals)
  if (url === '/optional-categories') return response(config, optionals.map((o, i) => ({ id: `cat${i}`, code: o.category, name: o.category, display_order: i })))
  if (url === '/product-groups') return response(config, [{ id: 'g1', name: 'Living', ipi: 5 }, { id: 'g2', name: 'Jantar', ipi: 5 }])
  if (url === '/product-types') return response(config, [...new Set(products.map(p => p.type))].map((name, i) => ({ id: `t${i}`, name, group_id: i < 3 ? 'g1' : 'g2' })))
  if (url === '/orders') return response(config, orders, { 'x-has-more': 'false' })
  if (url === '/orders/history' || url.endsWith('/history')) return response(config, [])
  if (url.startsWith('/orders/')) return response(config, byId(orders, url) ?? orders[0])
  if (url === '/dashboard/overview') return response(config, { start_date: '2026-01-01', end_date: '2026-08-13', granularity: 'month', metrics: { revenue_total: 268400, revenue_finalized: 214700, revenue_open: 53700, revenue_cancelled: 0, orders_total: 31, orders_finalized: 25, orders_open: 6, orders_cancelled: 0 }, chart: ['Fev','Mar','Abr','Mai','Jun','Jul','Ago'].map((key, i) => ({ key, revenue: 24000 + i * 4800, orders: 2 + i })), representatives: [{ name: 'André Menezes', orders: 18, revenue: 152800 }, { name: 'Bianca Rocha', orders: 13, revenue: 115600 }], products: products.slice(0, 4).map((p, i) => ({ product_code: p.product_code, description: p.description, quantity: 12 - i * 2, revenue: Number(p.price) * (12 - i * 2) })) })
  if (url === '/privacy/retention-reviews' || url === '/privacy/legal-holds' || url === '/privacy/incidents') return response(config, [])
  if (url.startsWith('/utils/cep/')) return response(config, { cep: '01415-001', logradouro: 'Alameda Santos', bairro: 'Cerqueira César', localidade: 'São Paulo', uf: 'SP' })
  return response(config, config.data ? JSON.parse(String(config.data || '{}')) : {})
}
export function installDemoAdapter() { if (DEMO_MODE) { api.defaults.adapter = adapter; authApi.defaults.adapter = adapter } }
